### ISSUE TITLE
EvalRefresh Error - err: json: cannot unmarshal array into Go value

### ISSUE THREAD

**Issue by acalbazana** [Mastercard/terraform-provider-restapi#109]
I receive the following error when applying my tf config:

...
_account_plan: Refreshing state... [id=0a32584d-6abc-4cdc-a827-b552683b5999]
2020/11/13 14:26:40 [ERROR] eval: *terraform.EvalRefresh, err: json: cannot unmarshal array into Go value of type map[string]interface {}

This resource was created successfully.  However, on subsequent apply runs, it fails.  Not sure where to go from here...

Here is what state looks like:

# restapi_object.demo_account_plan:

resource "restapi_object" "demo_account_plan" {
    api_data        = {
        "ApiIds"            = "map[results:[]]"
        "DefaultPlan"       = "false"
        "Description"       = "The test plan"
        "Name"              = "TF Account Plan"
        "OrganizationUsage" = "0"
        "Quota"             = "100"
        "QuotaInterval"     = "DAY"
        "RateLimit"         = "1"
        "Uuid"              = "0a32584d-6abc-4cdc-a827-b552683b5999"
        "__metadata"        = "map[uri:https://apim-ssg.test.foo.com:9443/developersdev/AccountPlans('0a32584d-6abc-4cdc-a827-b552683b5999')]"
    }
    api_response    = jsonencode(
        {
            ApiIds            = {
                results = []
            }
            DefaultPlan       = false
            Description       = "The test plan"
            Name              = "TF Account Plan"
            OrganizationUsage = "0"
            Quota             = 100
            QuotaInterval     = "DAY"
            RateLimit         = 1
            Uuid              = "0a32584d-6abc-4cdc-a827-b552683b5999"
            __metadata        = {
                uri = "https://apim-ssg.apimdev.test.com:9443/developersdev/AccountPlans('0a32584d-6abc-4cdc-a827-b552683b5999')"
            }
        }
    )

**Comment by DRuggeri** [comment]
Hi, @acalbazana. Thanks for checking in.
Yeah, the go errors can be pretty cryptic. It looks like you are pretty close - some quick pointers:
* You do not want to set the `api_response`... that should be an error condition. I wonder why terraform didn't complain
* The error you are getting is because a GET to the path that is resolved after creating the resource is an array rather than a hash. The response must be a well-formed JSON object for this provider to work.

If addressing those two items doesn't help, perhaps take a look at the debug output to see what request is being made and the response that comes back

**Comment by acalbazana** [comment]
Circling back to this... I understand what's happening here.  The vendor's API is a little inconsistent with how it addresses resources.  It is expecting a slightly different path to access a singular resource otherwise, it returns the collection.  Adding a read_path solved my issue.  

Can you elaborate a little more on your first bullet though? I'm not sure I follow...

Anyway, thanks for pointing me in the right direction.

**Comment by DRuggeri** [comment]
Sure, @acalbazana - sorry for the slow reply. The `api_response` field shouldn't be set by you because it will hold the actual results of the API call. That is: the value of that field is written by the provider in case you'd like to use the raw API response data in some other resource.

If you have a working recipe for an API provider that is a little inconsistent, it'd be cool if you could open a PR to the examples directory with something that works well for you and can perhaps help others that wander into the neighborhood that are also trying to work against that API.
