### ISSUE TITLE
(Documentation) Provider resource oauth_scopes is not optional according to the code

### ISSUE THREAD

**Issue by Thorln** [Mastercard/terraform-provider-restapi#120]
Oauth2 feature is a great addition, but the client code appears to require oauth_scopes (despite the documentation marking it as optional)

if opt.oauth_client_id != "" && opt.oauth_client_secret != "" && opt.oauth_token_url != "" && len(opt.oauth_scopes) > 0 {
		client.oauth_config = &clientcredentials.Config{

**Comment by DRuggeri** [comment]
Indeed - it doesn't look like Scopes is required in [clientcredentials](https://pkg.go.dev/golang.org/x/oauth2/clientcredentials) because the backing code just doesn't set it... but I believe that client ID, secret, and token URL are fundamentally needed by Oauth2.

I've gone ahead and updated this in 037f6beb6090cbc74d093b31a3e95cbd83d0e903 - thanks for the report!
