### ISSUE TITLE
Could set_resource_state do deep copy of obj.api_data?

### ISSUE THREAD

**Issue by rberlind** [Mastercard/terraform-provider-restapi#13]
I was wondering if set_resource_state might be able to do a deep copy of obj.api_data so that the actual object in Terraform would have nested fields under api_data that would be accessible with outputs and references from other resources.  Is this something you've investigated?

Would simply doing `api_data[k] = v` in set_resource_state() work? 

If not, would one of the deepCopyJSON functions suggested under https://stackoverflow.com/questions/51459083/deep-copying-maps-in-golang work?

**Comment by DRuggeri** [comment]
This is actually a feature I would love to have (hence the caveat in the doco about the current limitation). To be honest, I don't know if it is possible and would appreciate any research you can share. My assumption is that to be able to have a compound type in Terraform, [the structure of that type must be known ahead of time](https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/resource_api_object.go#L66) in the provider declaration with Terraform. I make this assumption because I haven't seen a complex, dynamic object in other providers yet.

Relevant link - This validation method for objects requires all keys to be known:
https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L1507

**Comment by rberlind** [comment]
Thanks.  I will research.  I work at HashiCorp and might be able to ask some Terraform experts.

**Comment by rberlind** [comment]
Hi @DRuggeri :  I had a discussion with several members of the Terraform team about this today.  They said this could not be done today with Terraform 0.11 because it does not allow an attribute to be declared as `map[string]interface{}` which is what would be needed to support this.

The deep copy I suggested would have broken the code because api_data is declared in https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/common.go#L59 as `map[string]string` and the nested strings could not themselves be maps.  In retrospect, that should have been obvious to me.

However, they did suggest that the situation might be better in Terraform 0.12 which is adding a jsondecode() function in connection with rich value types.  You might want to review https://www.hashicorp.com/blog/terraform-0-12-rich-value-types although that does not mention the jsondecode() function itself. A blog post that would have talked about jsonencode() and jsondecode() functions was planned, but not published for some reason.  I'm sure you'll be able to read about these functions when 0.12 is released.

So, I'm closing this for now. When 0.12 is released, we might want to revisit this.

**Comment by rberlind** [comment]
Here is a link to the current doc for the new jsondecode() function that is being developed: https://github.com/hashicorp/terraform/blob/2f93ef274103bbeb583a5905e832b6dcf4a88735/website/docs/configuration/functions/jsondecode.html.md

What I think this would allow us to do is store the api_data as a single JSON document and then use Terraform code to decode it and work with nested items no matter how deep.
