### ISSUE TITLE
Ignore and then capture the error response within `restapi_object`

### ISSUE THREAD

**Issue by marshall7m** [Mastercard/terraform-provider-restapi#139]
**Feature:**

Within the `restapi_object` create an option to ignore errored responses and to capture the error responses within the `restapi_object.foo.api_response` attribute or something along the lines of `restapi_object.foo.error_response`. 

**Use case:**
I'm experimenting with using the `restapi_object` to test an endpoint with an invalid `data` argument. Running `terraform apply` raises the error `│ Error: Unexpected response code '400':`.  The error is accurate although I would like to ignore the error and assert the error somewhere else within the Terraform configuration.

**Comment by DRuggeri** [comment]
Hi there, @marshall7m - thanks for contributing the idea.

Unfortunately, the principles of this provider are generally incompatible with the idea of ignoring an error when creating/managing an object. If an error occurs during creation, for example, the provider wouldn't know what it's managing going forward (because the object ID is not returned).

What I think you might be after is something that's even **more** generic than this provider: something that allows a user to fling requests at an API endpoint ignoring the rest. Perhaps that is worth adding as its own resource some day, but for now this isn't something that should be in this provider.
