### ISSUE TITLE
It seems when results_key is compared to search_value, it is case sensitive?

### ISSUE THREAD

**Issue by scastria** [Mastercard/terraform-provider-restapi#145]
Anyway to make the results_key comparison with search_value case INSENSITIVE?

**Comment by DRuggeri** [comment]
Hey there, @scastria - good question. At present, this is not possible because the [function](https://github.com/Mastercard/terraform-provider-restapi/blob/298e1d56e4a61f2897f81ce499aaee255424efda/restapi/common.go#L62-L130) that rummages around in the results is looking for specific keys by using golang's indexing methods (which are case sensitive). It would be possible to convert this to a case-insensitive indexing method by custom creating it, but it really should be as deterministic as possible.
