### ISSUE TITLE
Error: Internal validation failed. Object ID is not set

### ISSUE THREAD

**Issue by aman1505** [Mastercard/terraform-provider-restapi#158]
Hi Team,

I am trying to post a message to slack channel using slack incoming webhook URLs . Below is the tf file 

```
provider "restapi" {
  uri                  = "https://hooks.slack.com"
  debug                = true
  write_returns_object = true
}

```

```
resource "restapi_object" "post_slack" {
  path = "/services/AAAAAAAA/BBBBBBBB/CCCCCCCC"
  data = "{ \"text\": \"hello world\" }"
}
```
Even though the message is posted to the channel but I am getting the below ERROR - 

```
Error: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!
│ 
│   with restapi_object.post_slack,
│   on main.tf line 14, in resource "restapi_object" "post_slack":
│   14: resource "restapi_object" "post_slack" {
```

As per slack documenation the CURL request would look like - 

```
curl -X POST -H \
'Content-type: application/json' \
--data '{"text":"Hello, World!"}' \
https://hooks.slack.com/services/AAAAAAAA/BBBBBBBB/CCCCCCCC
```
@burbon @DRuggeri

**Comment by aman-db** [comment]
hi Team, It will be really helpful if you could please take a look into this issues ?

**Comment by DRuggeri** [comment]
Hi, @aman-db. Thanks for checking in. I think you are trying to use the provider beyond its intended purpose. The provider is made to manage objects on an API server rather than to serve as a generic API client to arbitrary services. As such, the provider expects a POST/PUT to create an object that will then be managed by Terraform through it's lifecycle - so this use case doesn't seem appropriate.

What I would suggest is taking a look at the [Terraform External](https://registry.terraform.io/providers/hashicorp/external/latest) provider.
