### ISSUE TITLE
Support for Data in URL encode format

### ISSUE THREAD

**Issue by jpmonge86** [Mastercard/terraform-provider-restapi#168]
Hello,

Wondering if there is way to pass in data in raw format (not json), for API methods in which URL encode is needed.

grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=apikeyvalue

Example with API params > https://cloud.ibm.com/apidocs/iam-identity-token-api#gettoken-apikey

I know passing empty data is not an option today, so looking for an option to include these and going around the json validation.

**Comment by DRuggeri** [comment]
Hi, @jpmonge86
Thanks for the suggestion. At present, this isn't something the provider is aiming to support because the data in the payload is very important to the internal structures of the provider (we use the response data to figure out what the ID is of the created object, for example).

Sticking with JSON seems to cover the most use cases, but I suppose a possible enhancement would be to abstract the serialization and parsing of data to other functions (to support JSON, URL Encode, YAML, etc)... but that would require biting off a fair bit of work for a provider intended to stay simple. For now, I think it's fair to say that we cannot support this use case because of being hitched to JSON.

**Comment by jpmonge86** [comment]
I understand. Thanks @DRuggeri
