### ISSUE TITLE
[restapi_object] json payload starting and ending with square braces [ ] is not accepted as data payload

### ISSUE THREAD

**Issue by inviul** [Mastercard/terraform-provider-restapi#175]
```
resource "restapi_object" "rest_api_at" {
  provider = restapi.pipeline
  path = "?api-version=7.1-preview.1"
  data = "[ { \"resource\" : { \"type\" : \"endpoint\", \"id\" : \"47845-uyyuteu\", \"name\" : \"Default\" }, \"pipelines\" : [ { \"id\" : 13894, \"authorized\" : true } ] } ]"
}
```

My payload contains square braces at begining and ending of the json data. 

Following error is coming:

_`Error: data attribute is invalid JSON: json: cannot unmarshal array into Go value of type map[string]interface {}`_

**Comment by DRuggeri** [comment]
Hi, @inviul. Thanks for taking the time to share the issue. You are correct - the restapi provider supports only a JSON object in the payload rather than an array. This is a requirement for the various options in the provider to work so we can reference the items in the data element (and aligns with the api_"object" intent).

I'm afraid this is a use case that cannot be supported.
