### ISSUE TITLE
Json Array is invalid

### ISSUE THREAD

**Issue by IronMania** [Mastercard/terraform-provider-restapi#198]
Provider will not use correct json if json is an array (that is valid json).

```
resource "restapi_object" "test" {
  path = ""
  data = "[{\"op\": \"add\",\"path\":\"/fields/System.Title\",\"from\": null,\"value\":\"Sample task\"}]"
}
```

`terraform plan` will output the fallowing error:

```
╷
│ Error: data attribute is invalid JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
│ 
│   with restapi_object.test,
│   on main.tf line 18, in resource "restapi_object" "test":
│   18:   data = "[{\"op\": \"add\",\"path\":\"/fields/System.Title\",\"from\": null,\"value\":\"Sample task\"}]"
│ 
╵
```

**Comment by DRuggeri** [comment]
Hi, @IronMania - this is expected behavior because the provider expects to operate on JSON objects on (rather than arrays of objects).

**Comment by IronMania** [comment]
@DRuggeri then please update the docoumentation. This is valid json. I need to send that data as JSON Patch and my api requires it.

**Comment by DRuggeri** [comment]
Sure, @IronMania - understood. Given the architecture of how this provider works, that would be a non-trivial change, but I welcome PRs or suggestions on how to achieve that goal.

I've modified the output of the config values in 92a2f30d9b79305a49a51da4fadfddbba93f8dd9 to be more clear. Otherwise, I detected that `object` was used pretty consistently across the rest of the project
