### ISSUE TITLE
500 Internal Server errors shouldn't invalidate resource

### ISSUE THREAD

**Issue by mlosapio** [Mastercard/terraform-provider-restapi#34]
Getting a 500 Internal Server error shouldn't invalidate a resource but rather trigger a fault or a retry. 

https://github.com/Mastercard/terraform-provider-restapi/blob/a13497c54310cc583480f5603fc0810f5b908dbb/restapi/resource_api_object.go#L207

**Comment by mlosapio** [comment]
This may be fixed already

**Comment by DRuggeri** [comment]
It makes a lot of sense for the 5xx range to be considered transient failures on the client side. Can you elaborate a bit on what you meant by "trigger a fault"? It sounds like you think there may be a more graceful way to fail.

**Comment by DRuggeri** [comment]
Thanks for the PR, too. I've added some comments/thoughts in #36

**Comment by robstonham-pa** [comment]
Can I also add another use case to this issue.
I just had my AuthToken expire when I did a "terraform refresh".  Every resource came back with a "401 UNAUTHORIZED" response and promptly wiped out my terraform state.

Could the fix for issue be expanded to allow a user supplied list of status codes to be considered transient failures rather than removing the resource?

**Comment by DRuggeri** [comment]
I was having a hard time figuring out why the error was not propagating (since anything that isn't a 200 is an error) and realized a small error in the go code that had a big impact.

The line `if err := obj.read_object(); err == nil {` should have been `if err = obj.read_object(); err == nil {`. The subtle difference is the change from `:=` to `=`. I did not realize this, but golang will allow you to create duplicate named variables in this syntax that do not survive the body of the if block.

To prevent future occurrences of this, I've stopped relying on that go idiom.

The end result was that errors triggered during the check for existence got swallowed and the default of `false` was used since there were no resulting errors.

The fix was just released in `v1.9.2`. I'll close this issue, but we can continue the retry conversation in the PR.
