### ISSUE TITLE
Use case with authentication

### ISSUE THREAD

**Issue by 5mzJyf6m** [Mastercard/terraform-provider-restapi#37]
Hello, I'm trying to use this provider with HPE OneView API which uses user authentication to generate a token. 
Using postman, I post json data in the body with username, password, and authLoginDomain to get the token which I then use in the header using "Auth" for subsequent requests which use json in the body. 
My attempts to get this working are not yet successful. I'm wondering if this provider is appropriate for this API? 
I have tried hard coding the token and making the config match the API documentation. 
Perhaps I'm missing something in my setup for this provider... here is my .tf.

provider "restapi" {
  uri = "https://10.0.0.3/rest/"
  insecure             = true
  debug                = true
  write_returns_object = true
  headers {
    "Content-Type"    = "application/json"
    "x-api-version"     = 1000
    "Auth"                    = "randomstringofcharacters1234567"
  }
}

resource "restapi_object" "authenticate" {
  path = "login-sessions"
  data = "{ \"userName\": \"${var.apiusername}\", \"password\": \"${var.apipassword}\", \"authLoginDomain\": \"local\"}" 

terraform plan gives me this error with or without the resource "restapi_object" block.
* provider.oneview: Post /rest/login-sessions: unsupported protocol scheme ""

**Comment by DRuggeri** [comment]
Hi, @5mzJyf6m. It's very hard to say. Each API has its own nuances. If I understand correctly, you want to use this provider to perform an authentication action and also to just interact with the rest objects on the API.

This provider probably isn't appropriate for the login action which generates the token because terraform will try to manage the object (in your tf case, `resource.restapi_object.authenticate`). So... even if the login portion worked about as expected, it would likely fail during other parts of the lifecycle. However, there is some prior art from @TMaYaD in #24 on how to do this with an external script. Basically, if you can distill the token retrieval portion down to a curl command, the provider should work for the rest.

**Comment by 5mzJyf6m** [comment]
Thank you kindly.
