### ISSUE TITLE
Allow application/x-www-form-urlencoded Body for Write Operations

### ISSUE THREAD

**Issue by enummela** [Mastercard/terraform-provider-restapi#47]
This is a proposal to add support for write operations to send the request body as `application/x-www-form-urlencoded` data. Currently the request body is limited to `application/json` data. If this proposal is implemented, then it will allow this provider to interact with a greater subset of REST APIs, such as [Pingdom's REST API](https://www.pingdom.com/api/2.1/).

From a user's perspective, the `restapi_object` could gain an additional argument `write_content_type`. This new argument's values would be restricted to `json` (default) and `x-www-form-urlencoded`. Alternatively, a new argument `write_request_body` could be added that overrides the request body generated from the `data` argument, allowing the request body for write operations to be formatted arbitrarily. The latter alternative would open up this provider to interact with even more content types than `application/json` and `application/x-www-form-urlencoded`.

**Comment by DRuggeri** [comment]
Hi, @enummela, thanks for the feedback! I think I understand the idea, but I don't know if it would be possible with this provider because it is very much tied to structured data coming back from the JSON response.

HOWEVER... maybe not all is lost? If I read the doco for Pingdom correctly, you might be able to provide all the data you need in query string parameters which could be used in `create_path`. You can maybe then manipulate the `read_path`, `update_path` and `delete_path` to achieve similar goals. It looks like this API will return valid JSON, so the provider itself ought to be happy(ish).... but I'm not sure that this provider would be the right tool for the job since the suggestion above would require some gymnastics.

**Comment by enummela** [comment]
Hi @DRuggeri, thanks for replying! I can understand if my proposal is out of the scope of this project.

Looking again at Pingdom's API, I think you're right about it being possible to provide all of the necessary parameters via the query string. I will experiment with the approach you suggested using this provider.
