### ISSUE TITLE
Float value in api_data  return exponential format

### ISSUE THREAD

**Issue by cnguyenp** [Mastercard/terraform-provider-restapi#48]
We have data return from Smartsheet API with this format. 
`"data": [
        {
            "id": 7243977842812804,
            "name": "Webhook Tube Life Estimate Listener",
            "scope": "sheet",
            "scopeObjectId": 8562070036735876,
            "events": [
                "*.*"
            ],
            "callbackUrl": "https://api.bluecentral-test.io/webhook/sheets",
            "sharedSecret": "6es3m789ebor0ewabxivj1czw0",
            "enabled": true,
            "status": "ENABLED",
            "version": 1,
            "createdAt": "2019-07-01T18:05:24Z",
            "modifiedAt": "2019-07-08T22:31:43Z"
        }]`

When we try to access `id` or `scopeObjectId`, value of these fields have been converted to 7.243977842812804e+15 and 8.562070036735876e+15. Is this an expected result?

**Comment by DRuggeri** [comment]
Hello. Yes, I suppose this is expected behavior. This is mentioned in the readme as "Currently the value is the golang fmt package's representation of the value" when describing the `api_data` field. So, if returned as a JSON number in the API response, I believe golang will parse it to a float32 or float64 internally. I reckon this is how the `fmt` package will display these data types at this length.

Relevant code:
https://github.com/Mastercard/terraform-provider-restapi/blob/d2a699d7c8ffcf2d4f2e60e98c7e7c458c8bdb77/restapi/common.go#L17

**Comment by cnguyenp** [comment]
I am wondering if you can change it to return the right string format?
