### ISSUE TITLE
data restapi_object return: Failed to find an object with the key

### ISSUE THREAD

**Issue by cnguyenp** [Mastercard/terraform-provider-restapi#49]
We try to query Smartsheet API with this code:
`
data "restapi_object" "data_webhook1" {
      provider = "restapi.get"
      path = "/webhooks"
       search_key = "scopeObjectId"
      search_value = "${var.sheet1}"
      results_key = "data"
     id_attribute = "id"
}
`

It is working if there is a match otherwise it will throw `Failed to find an object with the scopeObjectId key`. Is there a better way to handle/bypass  this error? Could it return `null`  if it doesnot exist?

Our goal is to try to check whether this data exists, then we can create/update this record accordingly.

**Comment by DRuggeri** [comment]
Hi there. If you want to test and repair (see if it exists and create if it doesn't), you should use the resource rather than the datasource. The datasource exists to read from something outside of terraform's control while the resource manages the object.

Is there a feature or behavior in the datasource that you think it might be a better fit?

**Comment by cnguyenp** [comment]
No, I just test out some code. Thank you for your suggestion.
