### ISSUE TITLE
update_method and create_method must be set to PUT in order to create PUT provider

### ISSUE THREAD

**Issue by cnguyenp** [Mastercard/terraform-provider-restapi#50]
- In v1.9.2: 
- When I  use `update_method: PUT` in the provider and `update_path` in the resource. It returns 404 status. 
- However, if i use `update_method:PUT` and `create_method:PUT` in provider and `create_path` in the resource, it will work for the first run. On the second run it returns 404. 

- What am I missing on this PUT request?

case 1: provider:  PUT and resource : update_path
![update_path_on_put ](https://user-images.githubusercontent.com/35930087/61164160-c9a52000-a4c7-11e9-8e2b-db8bb2ce2083.png)

case 2: 
![create_pathon_2 puts](https://user-images.githubusercontent.com/35930087/61164195-20125e80-a4c8-11e9-9506-0627a37d1bc1.png)

_Originally posted by @cnguyenp in https://github.com/Mastercard/terraform-provider-restapi/issues/46#issuecomment-511069703_

**Comment by DRuggeri** [comment]
Let's continue the conversation in #46 - it looks config related.

**Comment by DRuggeri** [comment]
I misunderstood the intent - reopening.

I think it would help most to understand the workflow that your API server uses. Can you please describe it in more detail?

What I understand so far:
- Objects live under `/webhooks`
- To create an object, you use PUT to `/webhooks/<some ID fetched by a datasource>` per your config
- The provider returns a result in JSON and the ID of the object is in `result.id`
- You override what the API server responds with and force the internal ID to be `update_result_webhook1`
- On the second run, the provider asks `/webhooks/update_result_webhook1` for info, but gets a 404
- You're no longer talking about the Infoblox API, but rather some other API

What is particularly confusing, though, is why you reference a datasource (`data.restapi_object.get_webhook1.id`) from the resource that should be managing that object. There shouldn't be a datasource in play here that I know of.

I *think* you need to...
- Remove the datasource since you should create the object in the resource, not out of band
- stop setting `id_attribute` and let the create action get the ID from the result

I strongly encourage following the readme to produce debug logs. If you understand the API you're working with a bit, seeing how the provider interacts with it through the debug logs should provide a lot of insight into how the configuration values come into play.

**Comment by cnguyenp** [comment]
My intention is to update the object with ID, and I need to set `update_method` and  `create_method` to PUT for the provider and use `create_path` on resource to update the object. 

Does that setup require?

**Comment by DRuggeri** [comment]
Sorry for the slow reply, @cnguyenp, I missed your message. I'm afraid I don't fully understand. I think it would be best to enable debug logging and see what the API is saying in response to your creation attempt and compare that to the values used in the configuration. Hopefully that provides some breadcrumbs to follow in order to locate the misconfiguration.

**Comment by DRuggeri** [comment]
Closing this issue since it's been a while. Feel free to reopen with more information.
