### ISSUE TITLE
Batch GET Requests

### ISSUE THREAD

**Issue by vazkarvishal** [Mastercard/terraform-provider-restapi#52]
Hello,

I am trying to use this module to create a data source which polls our internal API to get a collection of services owned by a specific team. I am struggling to do this with the current GET data source as it expects specific Search keys, values and id attributes.

Is this module able to:
1. Call an endpoint like `example.com/team-name/services` which returns a list of all services owned by the specific team
2. Loop through this data source to perform further logic

**Comment by DRuggeri** [comment]
Hi, vazkarvishal;
   I'm afraid it doesn't offer that kind of capability because that would need to be something that Terraform would do. However, as is mentioned in #45, I'll be looking to make the raw JSON string available which might allow this at some point in the future.

I'll go ahead and close this issue in favor of that other one, but feel free to reopen it with additional info if I missed the question.
