### ISSUE TITLE
Set expected response type

### ISSUE THREAD

**Issue by parsleylion** [Mastercard/terraform-provider-restapi#57]
I am using the provider to post to an api that takes json and returns a string. The post works as expected but always returns 'Error json: cannot unmarshal string into Go value of type map[string]interface {}'. I would like to set the expected return type or ignore the response.

**Comment by DRuggeri** [comment]
Hi, @parsleylion;
   I think I understand your desire well, but I'm afraid the provider is written in a way such that it must have structured data. We will not be able to offer support for something like this.

   I'll close the issue since I think it's fairly straight-forward, but feel free to continue the conversation if I've missed something!
