### ISSUE TITLE
Requesting to elaborate with example for the listed config parameters

### ISSUE THREAD

**Issue by Antonynixson** [Mastercard/terraform-provider-restapi#59]
Hello There,

I'm very new to terraform restapi provider, Can anyone please help ?
could anyone please provide an example for the all config parameters,? It will be very very helpful for me

`Provider configuration`

> uri
> insecure
> username
> password
> headers
> use_cookies
> timeout
> id_attribute
> create_method
> read_method
> update_method
> delete_method
> copy_keys
> write_returns_object
> create_returns_object
> xssi_prefix
> debug

`Restapi resource configuration`

> path
> create_path
> read_path
> update_path
> destroy_path
> id_attribute
> object_id
> data
> force_new
> debug

`Restapi datasource configuration`

> path
> query_string
> search_key
> search_value
> results_key
> id_attribute
> debug

Thanks in advance,
Antonynixson I

**Comment by DRuggeri** [comment]
Hi, @Antonynixson. Providing a single example that uses all of these parameters is difficult since most are specialized for certain APIs. I would suggest starting with the basic examples in the examples directory to get an understanding first.

If you have examples after you've used the API, we'd love a pull request!
