### ISSUE TITLE
Support for MIME

### ISSUE THREAD

**Issue by 2-face** [Mastercard/terraform-provider-restapi#64]
Is there any plan to support MIME (`Content-Type: multipart/form-data`)?

**Comment by DRuggeri** [comment]
Hi, @2-face. No, this is not something that is planned. Top of mind, it may not be possible to work with this because the form data would have to be encoded before being sent and the form field name would be highly variable per API.

The provider would have to do the encoding since encoding it in the .TF file would break the provider completely :-)

I'm not opposed to the idea if I'm missing something, though. For now, I'll close the issue, but feel free to comment/reopen it if there's more to discuss.

Thanks!
