### ISSUE TITLE
Support for resource specific headers

### ISSUE THREAD

**Issue by mbrancato** [Mastercard/terraform-provider-restapi#76]
It would be nice to specify the headers (e.g. API Key) on a per-resource basis, as some resources may be unauthenticated.

More to this point, I'm working with an API that needs a `read_header` that is different. This is the login API, so the create operation does a POST, but the read operation needs to check the id / API key is still valid. The current `read_path` can be used, but this specific API requires that to be specified as well. I've seen a number of APIs do this or similar for the login process.

**Comment by DRuggeri** [comment]
It sounds like you are using this provider to handle the login action AND to manage resources, correct? 
It's tough to understand a bit because the details of the API login flow aren't entirely clear to me. Can you maybe talk through the login flow and how you have it configured in the provider? Given that performing login itself can be a unique flow when compared to the typical management of API objects, perhaps the right solution is to not use `api_object` to perform login actions, but rather something else (maybe a new datasource for this provider or some other provider).

**Comment by DRuggeri** [comment]
Closing this out for now, but if there's more to add, please feel free to reopen discussion here.
