### ISSUE TITLE
Return all response without search filter by data resource restapi_object

### ISSUE THREAD

**Issue by binlab** [Mastercard/terraform-provider-restapi#79]
Thanks for the provider!
I would ask, can I do request and return all response from `data.restapi_object` without using `search_key` and `search_value` which now are mandatory?

**Comment by DRuggeri** [comment]
Hi, @binlab. I'm not really opposed to the idea, per se, but the goal of this provider is to manage individual resources (which is why search results return just one). Perhaps the better tool for what you are attempting to accomplish is the [External](https://www.terraform.io/docs/providers/external/data_source.html) datasource coupled with some curl-ing?

**Comment by DRuggeri** [comment]
Closing this out for now, but if there's more to add, please feel free to reopen discussion here.
