### ISSUE TITLE
Allow data to be empty

### ISSUE THREAD

**Issue by rberlind** [Mastercard/terraform-provider-restapi#8]
Some APIs don't actually need any data sent to them to create objects.  It would be good to allow the data attribute on the resource to be empty or "".

**Comment by DRuggeri** [comment]
Hmm.... this seems odd. Can you give me an example API and what that might look like? Maybe something that accepts arguments as URL parameters instead of data?

**Comment by rberlind** [comment]
https://www.terraform.io/docs/enterprise/api/team-tokens.html#generate-a-new-team-token which generates a team token for a team within Terraform Enterprise.  No data is sent despite using POST since the team is specified in the URL and since each team can only have one token at a time.  See https://www.terraform.io/docs/enterprise/users-teams-organizations/service-accounts.html#team-service-accounts for more details.

**Comment by rberlind** [comment]
Hi @DRuggeri : This has been open a long time.  Have you thought about implementing it or letting me do a PR for it?  Or do you think letting data be empty will create too many complications in the code?

**Comment by DRuggeri** [comment]
Hi, @rberlind - my apologies. I've been thinking about this off and on for a while. It does make sense. I haven't dug into it, but I think the code may behave oddly if there is no data. My suspicion is that it will confuse the provider because it won't be able to "manage" an object (since, without data it cannot detect changes later on). I also know there are several checks for data being empty as a sign of an issue (though, as you point out, that can be mitigated by permitting it). Another additional concern that should be tested is whether it will be idempotent - I'd be concerned if every time terraform was run, the provider changed the token (for example).

I will say, though, as long as it doesn't significantly complicate the code, the use case makes sense. If you'd like to experiment with it and see if the idea can hold water, feel free to try it out and submit a PR. I guess the decision ultimately boils down to code complexity and `go test` being happy after the modifications.

**Comment by rberlind** [comment]
I'll experiment with it next week.  I won't have time this week.
Supporting getting IDs from the response header is more important to my customer who will hopefully be moving forward with purchase of Terraform Enterprise and would then end up using this provider. Currently, they are using my own fork that supports getting IDs from headers.

**Comment by DRuggeri** [comment]
This is a pretty old issue, so I'll close it for now. Happy to pick up the conversation later when time is available.

**Comment by rberlind** [comment]
No problem.  Thanks
