### ISSUE TITLE
How to make GET calls using this provider?

### ISSUE THREAD

**Issue by thir13en5** [Mastercard/terraform-provider-restapi#84]
The issue I am facing is when I use the restapi_object resource, the "data" field is required and not optional. Due to this any API call I make is treated as a POST req. How to configure this for just GET API calls?

**Comment by DRuggeri** [comment]
I think you may want to consider using the datasource this provider offers? This will allow you to 'search' an API for an object, which is usually a GET function. Otherwise, this provider is meant to fully manage objects in an API server, so it may be a bit overkill for what you are trying to accomplish.

I'll close this issue with the advice that the datasource is probably what you need, but feel free to reopen or ask additional questions.
