### ISSUE TITLE
datasource element sends additional redundant query to the API

### ISSUE THREAD

**Issue by BggClr** [Mastercard/terraform-provider-restapi#88]
### Example configuration
```
data "restapi_object" "entity" {
  path           = "/entity"
  query_string   = "name=uniqueName"
  search_key     = "name"
  search_value   = "uniqueName"
  results_key    = "data"
  id_attribute   = "id"
}
```

### Expected behavior
*Single* request sent to `https://api.example.com/entity?name=uniqueName`
### Actual behavior
*Two* requests sent:
* `https://api.example.com/entity?name=uniqueName`
* `https://api.example.com/entity/entityId`

In case of first request returrns data, but second API request is missing the entity is empty

**Comment by DRuggeri** [comment]
Hi there, @BggClr. This is actually expected behavior based on the REST semantics noted in `README`. The datasource is intended to perform a search operation to identify the ID of the object, and will then follow up with a GET to that object.

If you know the uniqueName in advance, and all data is able to be returned, perhaps the [external](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) data source is a better solution for you?
