### ISSUE TITLE
Terraform Import Question

### ISSUE THREAD

**Issue by dergraf** [Mastercard/terraform-provider-restapi#89]
Hello guys!

First, thank you for this great provider!

I wonder if you have a workaround for the following issue, related to an external API I have to use.
The API uses the following path schema: /path/to/my/resources/[ID].json 
While I am able to workaround the `.json` suffix using the create_/update_/destroy_path resource properties for `terraform apply`. The `terraform import` command writes an `"id": "[ID].json" in the imported instances in `terraform.tfstate`.

Do you know if there's a workaround which would provide the correct IDs after importing terraform resources?

Thanks!

**Comment by gangofnuns** [comment]
I am a little new at this, but it seems like you might be able to 
override the json object configurations at import time  using the 
methods described [here](https://www.terraform.io/docs/configuration/override.html) and [here](https://www.terraform.io/docs/configuration/syntax-json.html). 

I am experimenting with this myself in search of a similar solution, 
so would love to hear back if it helps. 

The [terraform console](https://www.terraform.io/docs/commands/console.html) also 
seems to help a little with experimenting.

Hope that helps.

**Comment by DRuggeri** [comment]
Hi, @dergraf. Sorry for the slooooow reply and I'm glad to hear you are liking the provider.

So, I think this is a limitation to how we have to import data with Terraform. The [import code](https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/resource_api_object.go#L127) is only able to take a full path because the data structure presented to the provider during import doesn't have all the attributes (such as `read_path`) that you've set :-(. I've looked around and cannot find a way to get to the parameters in question.

I'm afraid I don't know a fix for this limitation. I'll go ahead and close the issue, but if a solution becomes available, feel free to add comments or share more info. Thanks!
