### ISSUE TITLE
Option to treat connection refused as "does not exist"

### ISSUE THREAD

**Issue by stephenliberty** [Mastercard/terraform-provider-restapi#93]
Use case:

Deploying Kong. Need to make REST calls to set up various bits of it (proper REST API by the way, it's very refreshing). In the case that the Kong container was stopped, died, whatever, we can't get the current state of it. So all calls end up looking like..

`Error: Get "https://<snip>:8444/certificates/b671300c-79d6-436f-92e1-38335d4e8af4": dial tcp <snip>:8444: connect: connection refused`

In this case, obviously yes - the connection was refused because the container no longer exists. We should be able to treat this as the resource not existing and schedule creation - not just an HTTP failure + death.

**Comment by stephenliberty** [comment]
This also becomes problematic when the container is destroyed and we're trying to run a terraform destroy - it hangs on trying to read the items before destroying them.

**Comment by DRuggeri** [comment]
Hi there, @stephenliberty. I think the use case sounds like something worthy of investigation, but I don't think this provider is positioned to support it since the form of error is [buried](https://github.com/Mastercard/terraform-provider-restapi/blob/579232e4e5f018c895532fd2265b39cf111e9642/restapi/api_client.go#L233) a layer or two into the golang [httpClient library](https://golang.org/pkg/net/http/#Client.Do).

We would have to resort to inspecting the error message to determine which kinds of errors are "OK". This would complicate the state refresh logic. I'm sorry, but I don't think this is an option we should add to the provider.

Would it be possible to create a dependency in Terraform on the mechanism that manages the Kong containers? This way, should the containers die off, the container orchestrator could trigger a redeployment? (apologies - I'm not very familiar with Kong deployment mechanisms)

Also - you can use the `timeout` parameter to reduce the time the provider will wait for a response during HTTP actions. If no value is set, I *think* the OS defaults will kick in which may be a lot depending on the platform. I usually set this to 3 seconds for internal networks since that's usually more than enough for an HTTP round trip.
